# Generated by Django 4.2.1 on 2024-02-15 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_title', models.CharField(max_length=255)),
                ('visitor_title_uz', models.CharField(max_length=255, null=True)),
                ('visitor_title_ru', models.CharField(max_length=255, null=True)),
                ('visitor_title_en', models.CharField(max_length=255, null=True)),
                ('visitor_count', models.PositiveIntegerField(default=1)),
            ],
        ),
    ]
