# Generated by Django 4.2.1 on 2024-02-15 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=155)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Yaroqsiz telefon raqam!', regex='^\\d{9}$')])),
                ('message', models.TextField()),
            ],
        ),
    ]
