# Generated by Django 4.2.1 on 2024-02-16 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_rooms_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rooms',
            old_name='room',
            new_name='category',
        ),
    ]
