# Generated by Django 4.2.1 on 2024-02-16 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reviews',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='name_uz',
        ),
    ]
