# Generated by Django 4.2.1 on 2024-02-17 07:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_reviews_name_en_remove_reviews_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('phone_number', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator(message='Yaroqsiz telefon raqam!', regex='^\\d{9}$')])),
            ],
        ),
    ]
